CREATE TABLE ESTADOS(
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(400) NOT NULL,

    PRIMARY KEY(ID)
) ENGINE = InnoDB;

CREATE TABLE CIDADES(
	ID BIGINT NOT NULL AUTO_INCREMENT,
    ID_ESTADOS BIGINT NOT NULL,
    NOME VARCHAR(400) NOT NULL,


    PRIMARY KEY(ID),
    CONSTRAINT FK_ESTADOS_CIDADES FOREIGN KEY (ID_ESTADOS) REFERENCES ESTADOS(ID)
) ENGINE = InnoDB;