
CREATE TABLE RESTAURANTES_USUARIOS (
	ID_RESTAURANTES BIGINT NOT NULL,
	ID_USUARIOS BIGINT NOT NULL,

	PRIMARY KEY (ID_RESTAURANTES,ID_USUARIOS),
    CONSTRAINT FK_REST_USUARIOS_RESTAURANTES FOREIGN KEY(ID_RESTAURANTES) REFERENCES RESTAURANTES(ID),
	CONSTRAINT FK_REST_USUARIOS_USUARIOS FOREIGN KEY(ID_USUARIOS) REFERENCES USUARIOS(ID)
);