CREATE TABLE PEDIDOS(

	ID BIGINT NOT NULL AUTO_INCREMENT,
	STATUS VARCHAR(50),
	TAXA_FRETE DECIMAL(10,2),
	VALOR_TOTAL DECIMAL(10,2),
	DATA_CRIACAO DATETIME,
	DATA_CONFIRMACAO DATETIME,
	DATA_CANCELAMENTO DATETIME,
	DATA_ENTREGA DATETIME,
	SUB_TOTAL DECIMAL(10,2),

	ID_USUARIOS BIGINT,
	ID_ENDERECO_CIDADE BIGINT,
	ID_FORMAS_PAGAMENTO BIGINT,
	ID_RESTAURANTES BIGINT,

	ENDERECO_CEP VARCHAR(50),
	ENDERECO_LOGRADOURO VARCHAR(200),
	ENDERECO_NUMERO VARCHAR(10),
	ENDERECO_COMPLEMENTO VARCHAR(500),
	ENDERECO_BAIRRO VARCHAR(200),

	PRIMARY KEY (ID),
	CONSTRAINT FK_USUARIOS_PEDIDOS FOREIGN KEY(ID_USUARIOS) REFERENCES USUARIOS(ID),
	CONSTRAINT FK_ENDERECO_CIDADE_PEDIDOS FOREIGN KEY(ID_ENDERECO_CIDADE) REFERENCES CIDADES(ID),
	CONSTRAINT FK_FORMAS_PAGAMENTO_PEDIDOS FOREIGN KEY(ID_FORMAS_PAGAMENTO) REFERENCES FORMAS_PAGAMENTO(ID),
	CONSTRAINT FK_RESTAURANTES_PEDIDOS FOREIGN KEY(ID_RESTAURANTES) REFERENCES RESTAURANTES(ID)

);
