CREATE TABLE ITENS_PEDIDOS(

	ID BIGINT NOT NULL AUTO_INCREMENT,
	ID_PRODUTOS BIGINT,
	ID_PEDIDOS BIGINT,
	PRECO_UNITARIO DECIMAL(10,2),
	PRECO_TOTAL DECIMAL(10,2),
	OBSERVACAO VARCHAR(200),
	QUANTIDADE BIGINT,


	PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUTOS_ITENS_PEDIDOS FOREIGN KEY(ID_PRODUTOS) REFERENCES PRODUTOS(ID),
	CONSTRAINT FK_PEDIDOS_ITENS_PEDIDOS FOREIGN KEY(ID_PEDIDOS) REFERENCES PEDIDOS(ID)
);
